name: Release from tag

on:
  push:
    tags:
      - '*'

jobs:
  create-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Create Release
        uses: ghalactic/github-release-from-tag@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
